FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY AtendimentoCampo.Api/*.csproj AtendimentoCampo.Api/
RUN dotnet restore AtendimentoCampo.Api/AtendimentoCampo.Api.csproj
COPY AtendimentoCampo.Api/ AtendimentoCampo.Api/
RUN dotnet publish AtendimentoCampo.Api/AtendimentoCampo.Api.csproj -c Release -o /app --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app .
EXPOSE 8080
ENTRYPOINT ["dotnet", "AtendimentoCampo.Api.dll"]
